blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archive'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.categories, name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.get_posts_by_tag, name='tag'),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'', include('comments.urls', namespace='comment')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


class Category(models.Model):
    """
    CharField 字符类型
    DateTimeField 日期时间类型
    IntegerField 整数类型
    其他：https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    # 摘要，允许为空
    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)
    is_delete = models.IntegerField(default=1)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title if len(self.title) > 20 else self.title[:20]

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 重写save方法，此方法并不算好
    # def save(self, *args, **kwargs):
    #     # 没有摘要的情况下
    #     if not self.excerpt:
    #         # 实例化一个Markdown类，渲染body
    #         md = markdown.Markdown(extensions=[
    #             'markdown.extensions.extra',
    #             'markdown.extensions.codehilite',
    #         ])
    #         # 先将Markdown渲染成html
    #         # strip_tags 去掉html里面的html标签，
    #         # 然后截取54个字符赋值给excerpt
    #         self.excerpt = strip_tags(md.convert(self.body))[:54]
    #     # 调用父类的save方法存储数据
    #     super().save(*args, **kwargs)

    class Meta:
        ordering = ['-create_time']

comments/models.py
from django.db import models


class Comments(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms
from .models import Comments

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'email', 'url', 'text']

blog/views.py
from django.shortcuts import render, get_object_or_404
from comments.forms import CommentForm
from .models import Post, Category, Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import markdown


def index(request):
    all_posts = Post.objects.all()
    return posts_paginator(all_posts, request)


def posts_paginator(all_posts, request):
    """ 文章分页 """

    # 10篇文章分页
    paginator = Paginator(all_posts, 10)
    page = request.GET.get('page')
    try:
        page = int(page) if page else 1
    except TypeError:
        page = 1
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:  # 如果页码太大，没有相应的记录
        posts = paginator.page(paginator.num_pages)  # 取最后一页的记录
    page_data = get_page_data(paginator.num_pages, page)
    return render(request, 'blog/index.html', context={'posts': posts, 'page': page_data})


def get_page_data(total, current_page_number):
    """ 计算分页相关数据 """

    # 上一页按钮是否可以按
    pre_button = True if int(current_page_number) > 1 else False
    # 下一页按钮是否可以按
    next_button = True if int(current_page_number) < total else False
    # 左侧显示的页数列表
    left_page_numbers = range(1, 4)
    # 右侧显示的页数列表
    right_page_numbers = [total - 2, total - 1, total]
    middle_page_numbers = []
    # 左侧省略号是否显示
    left_ellipsis = True
    # 右侧省略号是否显示
    right_ellipsis = False
    if total < 10:
        left_page_numbers = range(1, total + 1)
        left_ellipsis = False
        right_page_numbers = []

    else:
        if current_page_number < 6:
            if current_page_number > 2:
                left_page_numbers = range(1, current_page_number + 2)
                # if total - 2 > current_page_number:
                left_ellipsis = False
                right_ellipsis = True

        elif total - current_page_number > 4:
            right_ellipsis = True
            middle_page_numbers = [current_page_number - 1, current_page_number, current_page_number + 1]
        else:
            right_page_numbers = range(current_page_number - 1, total + 1)

    pre_page_number = current_page_number - 1 if current_page_number > 1 else 1
    next_page_number = current_page_number + 1 if current_page_number < total else total

    page_data = {'current_page': current_page_number, 'pre_button': pre_button, 'next_button': next_button,
                 'left_page_numbers': left_page_numbers, 'middle_page_numbers': middle_page_numbers,
                 'right_page_numbers': right_page_numbers, 'left_ellipsis': left_ellipsis,
                 'right_ellipsis': right_ellipsis, 'pre_page_number': pre_page_number,
                 'next_page_number': next_page_number}
    return page_data


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 阅读量+1
    post.increase_views()
    # markdown渲染detail
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc', ])
    form = CommentForm()
    comments = post.comments_set.all()
    context = {'post': post,
               'form': form,
               'comments': comments}
    return render(request, 'blog/detail.html', context=context)


def archives(request, year, month):
    """ 归档（按照年月） """
    posts = Post.objects.filter(create_time__year=year,
                                create_time__month=month
                                )
    return posts_paginator(posts, request)


def categories(request, pk):
    """ 目录 """
    category = get_object_or_404(Category, pk=pk)
    posts = Post.objects.filter(category=category)
    return posts_paginator(posts, request)


def get_posts_by_tag(request, pk):
    """ 标签 """
    tag = get_object_or_404(Tag, pk=pk)
    posts = Post.objects.filter(tags=tag)
    return posts_paginator(posts, request)

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import Comments
from .forms import CommentForm


def post_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comments_set.all();
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
    return redirect(post)

templates/blog/detail.html
{% extends 'layout.html' %}
{% block main %}

{#    <hr/>#}
<div class="col-md-9">
    <div class="blog-main">
        <div class="heading-blog">
            {{ post.title }}
        </div>
        {#        <img src="assets/img/1.jpg" class="img-responsive img-rounded"/>#}
        <div class="blog-info">
            <span class="label label-primary">{{ post.create_time }}</span>
            <span class="label label-danger">{{ post.author }}</span>
            <span class="label label-success">阅读：{{ post.views }}</span>
{#            <span class="label label-info">#}
{#            <i class="fa fa-thumbs-up"></i>+     10#}
{#            <i class="fa fa-thumbs-down"></i>-3#}
            <br/>
            <br/>
            {% for tag in post.tags.all %}
                <span class="label label-danger" {% if not forloop.first %} style="margin-left: 5px;" {% endif %}>
                    <a href="{% url 'blog:tag' tag.pk %}" style="color: #fff;">{{ tag.name }}</a>
                </span>
            {% endfor %}
        </span>
        </div>
        <div class="blog-txt" style="font-size:16px;color: #808080">
            {{ post.excerpt }}
        </div>
        <div class="blog-txt">
            {{ post.body | safe }}
        </div>


        <div style="margin-top: 20px">版权声明：本文为博主原创文章，转载请表明出处。</div>

    </div>
    <!--BLOG MAIN SECTION END-->
{#    <div>#}
{#        <form action="{% url 'comment:post_comment' post.pk %}" method="post" class="comment-form">#}
{#            {% csrf_token %}#}
{#            <div class="row">#}
{#                <div class="col-md-4">#}
{#                    <label for="{{ form.name.id_for_label }}">名字：</label>#}
{#                    {{ form.name }}#}
{#                    {{ form.name.errors }}#}
{#                </div>#}
{#                <div class="col-md-4">#}
{#                    <label for="{{ form.email.id_for_label }}">邮箱：</label>#}
{#                    {{ form.email }}#}
{#                    {{ form.email.errors }}#}
{#                </div>#}
{#                <div class="col-md-4">#}
{#                    <label for="{{ form.url.id_for_label }}">URL：</label>#}
{#                    {{ form.url }}#}
{#                    {{ form.url.errors }}#}
{#                </div>#}
{#                <div class="col-md-12">#}
{#                    <label for="{{ form.text.id_for_label }}">评论：</label>#}
{#                    {{ form.text }}#}
{#                    {{ form.text.errors }}#}
{#                    <button type="submit" class="comment-btn">发表</button>#}
{#                </div>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}


{#    <h3 style="margin-top: 50px"><strong>Recent Comments :</strong></h3>#}
{#    <hr/>#}
{#    <ul class="media-list">#}
{#        {% for comment in comments %}#}
{#            <li class="media">#}
{#                <div class="media-body">#}
{#                    <h4 class="media-heading">#}
{#                        <pre>{{ comment.name }}</pre>：#}
{#                        <time style="font-size: small; color: grey">{{ comment.create_time }}</time>#}
{#                    </h4>#}
{#                    <p>#}
{#                        <pre>{{ comment.text }}</pre>#}
{#                    </p>#}
{#                </div>#}
{#            </li>#}
{#        {% empty %}#}
{#            暂无评论#}
{#        {% endfor %}#}
        <!-- COMMENT SECTION - ONE END-->
        {#        <li class="media">#}
        {#            <a class="pull-left" href="#">#}
        {#                <img class="media-object img-circle" src="assets/img/user.gif"/>#}
        {#            </a>#}
        {#            <div class="media-body">#}
        {#                <h4 class="media-heading">Lorem ipsum dolor sit amet</h4>#}
        {#                <p>#}
        {#                    Donec sit amet ligula enim. Duis vel condimentum massa.#}
        {#                    Maecenas eget congue dui. Vestibulum et eros consectetur,#}
        {#                    interdum nibh et, volutpat dolor.#}
        {#                </p>#}
        {#                <!-- Nested media object -->#}
        {#                <div class="media">#}
        {#                    <a class="pull-left" href="#">#}
        {#                        <img class="media-object img-circle" src="assets/img/user2.png"/>#}
        {#                    </a>#}
        {#                    <div class="media-body">#}
        {#                        <h4 class="media-heading">Nulla gravida vitae neque </h4>#}
        {#                        Donec sit amet ligula enim. Duis vel condimentum massa.#}
        {#                        Maecenas eget congue dui. Vestibulum et eros consectetur,#}
        {#                        interdum nibh et, volutpat dolor.#}
        {#                        <!-- Nested media object -->#}
        {#                        <div class="media">#}
        {#                            <a class="pull-left" href="#">#}
        {#                                <img class="media-object img-circle" src="assets/img/user.gif"/>#}
        {#                            </a>#}
        {#                            <div class="media-body">#}
        {#                                <h4 class="media-heading">Donec sit amet ligula enim</h4>#}
        {#                                Donec sit amet ligula enim. Duis vel condimentum massa.#}
        {#                                Maecenas eget congue dui. Vestibulum et eros consectetur,#}
        {#                                interdum nibh et, volutpat dolor.#}
        {#                            </div>#}
        {#                        </div>#}
        {#                    </div>#}
        {#                </div>#}
        {#                <!-- Nested media object -->#}
        {#                <div class="media">#}
        {#                    <a class="pull-left" href="#">#}
        {#                        <img class="media-object img-circle" src="assets/img/user2.png"/>#}
        {#                    </a>#}
        {#                    <div class="media-body">#}
        {#                        <h4 class="media-heading">Vestibulum et eros consectetur</h4>#}
        {#                        Donec sit amet ligula enim. Duis vel condimentum massa.#}
        {#                        Maecenas eget congue dui. Vestibulum et eros consectetur,#}
        {#                        interdum nibh et, volutpat dolor.#}
        {#                    </div>#}
        {#                </div>#}
        {#            </div>#}
        {#        </li>#}
        <!-- COMMENT SECTION - TWO END-->
        {#        <li class="media">#}
        {#            <a class="pull-left" href="#">#}
        {#                <img class="media-object img-circle" src="assets/img/user.gif"/>#}
        {#            </a>#}
        {#            <div class="media-body">#}
        {#                <h4 class="media-heading">Vestibulum et eros consectetur</h4>#}
        {#                <p>#}
        {#                    Donec sit amet ligula enim. Duis vel condimentum massa.#}
        {#                    Maecenas eget congue dui. Vestibulum et eros consectetur,#}
        {#                    interdum nibh et, volutpat dolor.#}
        {#                </p>#}
        {#            </div>#}
        {#        </li>#}
        <!-- COMMENT SECTION - THREE END-->
{#    </ul>#}
    <!--COMMENTS SECTION END-->
</div>
{% endblock main %}

templates/blog/index.html
{% extends 'layout.html' %}
{% block main %}
{% load blog_tags %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% for post in posts.object_list %}
                <div class="blog-main">
                    <a href="{{ post.get_absolute_url }}">
                        <div class="heading-blog">
                            {{ post.title }}
                        </div>
{#                      <img src="{% static 'blog/img/1.jpg' %}" class="img-responsive img-rounded"/>#}
                    </a>
                    {% if post.excerpt %}
                        <a href="{{ post.get_absolute_url }}">
                            <div class="blog-txt">
    {#                            {{ post.excerpt | get_excerpt:post.body }}#}
                                {{ post.excerpt}}
                            </div>
                        </a>
                    {% endif %}
                    <div class="blog-info">
                        <span class="label label-primary">{{ post.create_time }}</span>
                        <span class="label label-danger">阅读：{{ post.views }}</span>
                        <span class="label label-success">评论：{{ post.comments_set.count }}</span>
                        {#                        <span class="label label-info">#}
{#                            <i class="fa fa-thumbs-up"></i>+ 10#}
{#                            <i class="fa fa-thumbs-down"></i>-3#}
{#                        </span>#}
                    </div>

                </div>
                {% empty %}
                    <div>还没有发布的文章</div>
                {% endfor %}
                <!--BLOG THREE END -->
                <nav>
                    <ul class="pagination">
                        <li {% if not page.pre_button %} class="disabled" {% endif %}>
                            <a {% if page.pre_button %} href="?page={{ page.pre_page_number }}" {% endif %}>
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>

                        {% if page.left_page_numbers %}
                            {% for page_number in page.left_page_numbers %}
                                <li {% if page.current_page == page_number %} class="active" {% endif %}>
                                    <a href="?page={{ page_number }}">
                                        {{ page_number }}
                                        <span class="sr-only"></span>
                                    </a>
                                </li>
                            {% endfor %}
                        {% endif %}

                        {%  if page.left_ellipsis %} <li><a>...<span class="sr-only"></span></a></li> {% endif %}

                        {%  if page.middle_page_numbers %}
                            {% for page_number in page.middle_page_numbers %}
                                <li {% if page.current_page == page_number %} class="active" {% endif %}>
                                    <a href="?page={{ page_number }}">
                                        {{ page_number }}
                                        <span class="sr-only"></span>
                                    </a>
                                </li>
                            {% endfor %}
                        {% endif %}

                        {%  if page.right_ellipsis %} <li><a>...<span class="sr-only"></span></a></li> {% endif %}

                        {% if page.right_page_numbers %}
                            {% for page_number in page.right_page_numbers %}
                                <li {% if page.current_page == page_number %} class="active" {% endif %}>
                                    <a href="?page={{ page_number }}">
                                        {{ page_number }}
                                        <span class="sr-only"></span>
                                    </a>
                                </li>
                            {% endfor %}
                        {% endif %}

                        <li {% if not page.next_button %} class="disabled" {% endif %}>
                            <a {% if page.next_button %} href="?page={{ page.next_page_number }}" {% endif %}>
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
{#                        <li><a href="?page={{ page.total }}">Last<span class="sr-only">Last</span></a></li>#}
                    </ul>
                </nav>
                <!--PAGING  END -->
            </div>
        </div>
    </div>
</section>
<hr/>

{% endblock main %}

templates/layout.html
{% load staticfiles %}
{% load blog_tags %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content="Simba Li"/>
    <link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}" />
    <meta name="baidu-site-verification" content="mi823HsgsA" />
    <meta name="360-site-verification" content="69733d4ecb46c93f180f72c0900c9276" />
    <meta name="keywords" content="Python,java,blog,李平新,教程" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Simba's Blog</title>
{#    <link href="{% static 'blog/css/bootstrap.css' %}" rel="stylesheet"/>#}
    <link href="https://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="{% static 'blog/css/font-awesome.css' %}" rel="stylesheet"/>
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet"/>
    <link href="{% static 'blog/css/highlights/github.css' %}" rel="stylesheet">
</head>
<body>


<section class="header-section">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <a href="{% url 'blog:index' %}">
                    <img src="{% static 'blog/img/headimage.jpg' %}" alt="头像" class="img-circle img-responsive"/>
                </a>
            </div>
            <div class="col-md-5 text-center">
                <h1><strong>Simba Li </strong></h1>
                <h4>Java Developer</h4>
            </div>
            <div class="col-md-5">
                <h3>WHO AM I :</h3>
                主业：Java开发。自学Python，开发了此博客
                <br />
                Email: <i><strong>lipingxin@outlook.com</strong></i>
            </div>
        </div>
    </div>
</section>
<!--HOME SECTION END-->
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-2 spon-txt"></div>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
            {% block main %}
            {% endblock main %}
            </div>
            <div class="col-md-3">

                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>Archives</strong>
                    </li>
                    {% archives as date_list %}
                    {% for date in date_list %}
                        <li class="list-group-item">
                            <span class="badge"></span>
                            <a href="{% url 'blog:archive' date.year date.month %}">
                                {{ date.year }}年{{ date.month }}月
                            </a>
                        </li>
                        {% empty %}
                        <li class="list-group-item">
                            <span class="badge">104</span>暂无归档
                        </li>
                    {% endfor %}

                    <li class="list-group-item">
                        <strong>Category</strong>
                    </li>
                    {% get_categories as categories %}
                    {% for category in categories %}
                        <li class="list-group-item">
                            <span class="badge">{{ category.post_set.count }}</span>
                            <a href="{% url 'blog:category' category.pk %}">
                                {{ category.name }}
                            </a>
                        </li>
                    {% empty %}
                    {% endfor %}

                    <li class="list-group-item">
                        <strong>Tags</strong>
                    </li>
                    {% get_tags as tags %}
                    {% for tag in tags %}
                        <li class="list-group-item">
                            <span class="badge">{{ tag.num_post }}</span>
                            <a href="{% url 'blog:tag' tag.pk %}">
                                {{ tag.name }}
                            </a>
                        </li>
                    {% empty %}
                    {% endfor %}
                </ul>
                <br/>
                </ul>
            </div>
        </div>
    </div>
</section>
<hr/>
<div class="container">
    <div>
        <p>友情链接：</p>
        <table border="0">
        <tr style="height: 30px">
            <td width="200px"><a target="_blank" href="http://zmrenwu.com">追梦人物的博客</a></td>
            <td width="200px"><a target="_blank" href="https://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000">廖雪峰的Python教程</a></td>
            <td width="200px"><a target="_blank" href="http://www.csdn.net">CSDN</a></td>
        </tr>
        <tr style="height: 30px">
            <td width="200px"><a target="_blank" href="https://www.aliyun.com">阿里云</a></td>
            <td width="200px"><a target="_blank" href="https://www.qiniu.com">七牛云</a></td>
            <td width="200px"><a target="_blank" href="https://github.com">GitHub</a></td>
        </tr>
        <tr style="height: 30px">
            <td width="200px"><a target="_blank" href="https://www.python.org">Python</a></td>
            <td width="200px"><a target="_blank" href="https://www.djangoproject.com">Django</a></td>
            <td width="200px"><a target="_blank" href="http://www.bootcss.com/">Bootstrap</a></td>
        </tr>
        </table>
    </div>
    <div class="row">
        <div class="col-md-12 text-center set-foot">
            <div style="width:300px;margin:0 auto; padding:10px 0;">
                <a target="_blank" href="http://www.miitbeian.gov.cn/">浙ICP备17050845号-1</a>
		 		<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010602008761" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">
                    <img src="{% static 'blog/img/beian.png' %}" alt="公安备案图标" style="float:left;"/>
                    <p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">浙公网安备 33010602008761号</p>
                </a>
		 	</div>
            Copyright © 2017 Simba's Blog. All Rights Reserved. lipingxin 版权所有
        </div>
    </div>
</div>

</body>
</html>